# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b2b3ba9fc96e9aa5f1390dd5f48727432249dc76d7942bef0061b904fc34e1623a580d04f675f262318e8ed1156a4f9ff439fd611b46cc42e81a99ec3357a0d

test:
  secret_key_base: cdd44db0afa05e468262f30ee25914412bacee52b9cc1c2642ce8481bbacf1cb19a50ec1538723ad332c59bbd6e2e396e6c5ba787fa3dcbe8fd96f7863574989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
